# Generated by Django 5.2.7 on 2025-11-29 20:02

import news_project.auth_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_project', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('tries', models.SmallIntegerField(default=0)),
                ('extra', models.JSONField(default=dict)),
                ('by', models.SmallIntegerField(choices=[(1, 'login'), (2, 'register')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', news_project.auth_models.CustomUserManager()),
            ],
        ),
    ]
