# Generated by Django 5.2.7 on 2025-12-05 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_project', '0004_otp_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='created_at',
            new_name='created',
        ),
    ]
